const CREDIT_AMOUNT_REQUEST = "CREDIT_AMOUNT_REQUEST";
const CREDIT_AMOUNT_SUCCESS = "CREDIT_AMOUNT_SUCCESS";
const CREDIT_AMOUNT_FAILURE = "CREDIT_AMOUNT_FAILURE";

export {
    CREDIT_AMOUNT_REQUEST,
    CREDIT_AMOUNT_SUCCESS,
    CREDIT_AMOUNT_FAILURE
}